name: basic
on: push
jobs:
    basic:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - run: make setup
            - run: make run
            - run: make test
            - run: make lint
